# Generated by Django 3.0.5 on 2020-04-16 19:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wholesaler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ftp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.FTP')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_stamp', models.DateTimeField(verbose_name='date created')),
                ('modified_stamp', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('transmit_stamp', models.DateTimeField(blank=True, null=True, verbose_name='date transmitted')),
                ('articles', models.CharField(max_length=100000, validators=[django.core.validators.int_list_validator])),
                ('wholesaler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scanner.Wholesaler')),
            ],
        ),
    ]
