# Generated by Django 3.0.5 on 2020-04-17 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wholesaler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='modified_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='positions',
            field=models.ManyToManyField(to='order.Position'),
        ),
        migrations.AddField(
            model_name='order',
            name='transmit_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transmit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='wholesaler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wholesaler.Wholesaler'),
        ),
    ]
