# Generated by Django 3.0.5 on 2020-04-18 10:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grosshaendler', '0001_initial'),
        ('artikel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menge', models.IntegerField(verbose_name='Menge')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artikel.Artikel')),
            ],
        ),
        migrations.CreateModel(
            name='Bestellung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(default=datetime.datetime.now)),
                ('bearbeitet', models.DateTimeField(auto_now=True)),
                ('uebertragen', models.DateTimeField(blank=True, null=True)),
                ('bearbeiter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bearbeiter', to=settings.AUTH_USER_MODEL)),
                ('ersteller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ersteller', to=settings.AUTH_USER_MODEL)),
                ('grosshaendler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grosshaendler.Grosshaendler')),
                ('positionen', models.ManyToManyField(to='bestellung.Position')),
                ('uebertrager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='uebertrager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
